#
# Aliases
#

echo "Loading aliases"

alias ls='ls --color=auto'
alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
alias sconfig='sudo /usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME'
alias setwal='~/.scripts/setwal.sh'
alias yt='~/.scripts/yt.sh'
alias m='devour mpv'
alias dgp='sudo devour gparted'
alias redunst='wal -Rsn; killall dunst; dunstify "Title" "This is a test notification"'

# Suckless
alias rcas='~/.scripts/suckless/rcas.sh' # Recompile all suckless utilities
alias rcdwm='~/.scripts/suckless/rcdwm.sh' # Recompile DWM
alias rcdm='~/.scripts/suckless/rcdm.sh' # Recompile dmenu
alias rcdwmb='~/.scripts/suckless/rcdwmb.sh' # Recompile DWMBlocks
alias rcst='~/.scripts/suckless/rcst.sh' # Recompile ST
